### ISSUE TITLE
Need to display google map properly in index__map section it should replace index__info when user is logged in

### ISSUE THREAD

**Issue by guledali** [pyroface/team-pineapple#10]
https://www.w3schools.com/html/html_googlemaps.asp

**Comment by guledali** [comment]
![screenshot 136 _li](https://user-images.githubusercontent.com/20647282/34781217-850e684a-f625-11e7-901f-9ede928ce04e.jpg)

**Comment by annaLarsson** [comment]
Added a google map

**Comment by guledali** [comment]
This was earlier closed but I'm opening in again, the google map should be responsive, should have it´s own section (index__map) play button is no longer relevant as user is logged(index__profile is displayed block) in see the map

**Comment by guledali** [comment]
![screenshot 151](https://user-images.githubusercontent.com/20647282/35046267-c0c48e20-fb96-11e7-8041-9190e308e5cb.png)


I'm closing this issue the map is now columns instead of pixels
